create table if not exists public.ativos (
  id bigint generated by default as identity primary key,
  nome text not null,
  tipo text not null,
  categoria text not null,
  patrimonio text,
  numero_serie text,
  codigo_barras text,
  status text not null,
  condicao_fisica text,
  unidade text not null,
  andar_sala text not null,
  mesa_estacao text not null,
  cidade text not null,
  responsavel_nome text,
  responsavel_email text,
  user_id uuid references auth.users(id),
  created_at timestamptz not null default now()
);

alter table public.ativos add column if not exists responsavel_nome text;
alter table public.ativos add column if not exists responsavel_email text;
alter table public.ativos add column if not exists user_id uuid references auth.users(id);

create unique index if not exists ativos_patrimonio_unique
on public.ativos (patrimonio)
where patrimonio is not null and patrimonio <> '';

create unique index if not exists ativos_numero_serie_unique
on public.ativos (numero_serie)
where numero_serie is not null and numero_serie <> '';

create table if not exists public.licencas (
  id bigint generated by default as identity primary key,
  software text not null,
  chave text,
  quantidade integer not null default 1,
  em_uso integer not null default 0,
  data_vencimento date,
  user_id uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create table if not exists public.softwares (
  id bigint generated by default as identity primary key,
  nome text not null,
  versao text not null,
  hostname text,
  identificador text,
  user_id uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create table if not exists public.ativo_softwares (
  id bigint generated by default as identity primary key,
  ativo_id bigint not null references public.ativos(id) on delete cascade,
  software_id bigint not null references public.softwares(id) on delete cascade,
  licenca_id bigint not null references public.licencas(id) on delete cascade,
  observacao text,
  user_id uuid references auth.users(id),
  created_at timestamptz not null default now()
);

alter table public.licencas add column if not exists software text;
alter table public.licencas add column if not exists chave text;
alter table public.licencas add column if not exists quantidade integer not null default 1;
alter table public.licencas add column if not exists em_uso integer not null default 0;
alter table public.licencas add column if not exists data_vencimento date;
alter table public.licencas add column if not exists user_id uuid references auth.users(id);

alter table public.softwares add column if not exists nome text;
alter table public.softwares add column if not exists versao text;
alter table public.softwares add column if not exists hostname text;
alter table public.softwares add column if not exists identificador text;
alter table public.softwares add column if not exists user_id uuid references auth.users(id);

alter table public.ativo_softwares add column if not exists ativo_id bigint references public.ativos(id) on delete cascade;
alter table public.ativo_softwares add column if not exists software_id bigint references public.softwares(id) on delete cascade;
alter table public.ativo_softwares add column if not exists licenca_id bigint references public.licencas(id) on delete cascade;
alter table public.ativo_softwares add column if not exists observacao text;
alter table public.ativo_softwares add column if not exists user_id uuid references auth.users(id);

alter table public.ativos enable row level security;
alter table public.licencas enable row level security;
alter table public.softwares enable row level security;
alter table public.ativo_softwares enable row level security;

drop policy if exists "Usuarios autenticados podem cadastrar ativos" on public.ativos;
drop policy if exists "Usuarios autenticados podem consultar seus ativos" on public.ativos;
drop policy if exists "Usuarios autenticados podem editar seus ativos" on public.ativos;
drop policy if exists "Usuarios autenticados podem excluir seus ativos" on public.ativos;
drop policy if exists "Usuarios autenticados gerenciam ativos" on public.ativos;
drop policy if exists "Usuários autenticados gerenciam ativos" on public.ativos;

create policy "Usuários autenticados gerenciam ativos"
on public.ativos
for all
to authenticated
using (true)
with check (true);

drop policy if exists "Usuarios autenticados gerenciam licencas" on public.licencas;
drop policy if exists "Usuarios autenticados gerenciam softwares" on public.softwares;
drop policy if exists "Usuarios autenticados gerenciam associacoes" on public.ativo_softwares;
drop policy if exists "Usuários autenticados gerenciam licenças" on public.licencas;
drop policy if exists "Usuários autenticados gerenciam softwares" on public.softwares;
drop policy if exists "Usuários autenticados gerenciam associações" on public.ativo_softwares;

create policy "Usuários autenticados gerenciam licenças"
on public.licencas
for all
to authenticated
using (true)
with check (true);

create policy "Usuários autenticados gerenciam softwares"
on public.softwares
for all
to authenticated
using (true)
with check (true);

create policy "Usuários autenticados gerenciam associações"
on public.ativo_softwares
for all
to authenticated
using (true)
with check (true);

update public.licencas
set em_uso = coalesce(associacoes.total, 0)
from (
  select licenca_id, count(*)::integer as total
  from public.ativo_softwares
  group by licenca_id
) as associacoes
where public.licencas.id = associacoes.licenca_id;
